name: TheWalls2
main: me.Hoot215.TheWalls2.TheWalls2
version: 1.7.2
author: Hoot215
softdepend: [Vault]
website: 'http://dev.bukkit.org/server-mods/thewalls2/'
permissions:
    thewalls2.*:
        description: "TheWalls2 의 모든 명령어를 엑세스할 수 있습니다"
        default: op
        children:
            thewalls2.default: true
            thewalls2.notify: true
            thewalls2.command.thewalls.start: true
            thewalls2.command.thewalls.stop: true
            thewalls2.command.thewalls.restoreworld: true
    thewalls2.default:
        description: "Gives access to defaults in TheWalls2"
        default: true
        children:
            thewalls2.command.thewalls: true
            thewalls2.command.thewalls.join: true
            thewalls2.command.thewalls.leave: true
            thewalls2.command.thewalls.team: true
    thewalls2.notify:
        description: "Receive notifications of plugin updates"
    thewalls2.command.thewalls:
        description: "Gives access to the command '/월즈'"
    thewalls2.command.thewalls.join:
        description: "Gives access to the command '/월즈 입장'"
    thewalls2.command.thewalls.leave:
        description: "Gives access to the command '/월즈 퇴장'"
    thewalls2.command.thewalls.team:
        description: "Gives access to the command '/월즈 팀 <1-4>'"
    thewalls2.command.thewalls.start:
        description: "Gives access to the command '/월즈 시작'"
    thewalls2.command.thewalls.stop:
        description: "Gives access to the command '/월즈 종료'"
    thewalls2.command.thewalls.restoreworld:
        description: "Gives access to the command '/월즈 월드복구'"
commands:
    월즈:
        description: "TheWalls2 의 도움말을 표시합니다"
        permission: thewalls2.command.thewalls
        permission-message: "You don't have <permission>"
        usage: "/월즈 [Sub-Command]"
        aliases: [tw, twalls]